/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafico;

/**
 *
 * @author ap550
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTeclas = new javax.swing.JPanel();
        cuadro = new javax.swing.JTextField();
        Q = new javax.swing.JButton();
        W = new javax.swing.JButton();
        E = new javax.swing.JButton();
        R = new javax.swing.JButton();
        T = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        U = new javax.swing.JButton();
        I = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        A = new javax.swing.JButton();
        S = new javax.swing.JButton();
        D = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        Ñ = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        X = new javax.swing.JButton();
        C = new javax.swing.JButton();
        V = new javax.swing.JButton();
        B = new javax.swing.JButton();
        N = new javax.swing.JButton();
        M = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Intentos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelIMG = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PanelTeclas.setBackground(new java.awt.Color(255, 255, 204));
        PanelTeclas.setBorder(new javax.swing.border.MatteBorder(null));
        PanelTeclas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuadro.setBackground(new java.awt.Color(255, 255, 255));
        cuadro.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        cuadro.setForeground(new java.awt.Color(0, 0, 0));
        PanelTeclas.add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 330, 39));

        Q.setBackground(new java.awt.Color(102, 0, 0));
        Q.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        PanelTeclas.add(Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 50));

        W.setBackground(new java.awt.Color(102, 0, 0));
        W.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        PanelTeclas.add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, 50));

        E.setBackground(new java.awt.Color(102, 0, 0));
        E.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        PanelTeclas.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 50));

        R.setBackground(new java.awt.Color(102, 0, 0));
        R.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        R.setText("R");
        R.setToolTipText("");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        PanelTeclas.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 50));

        T.setBackground(new java.awt.Color(102, 0, 0));
        T.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        PanelTeclas.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 50, 50));

        Y.setBackground(new java.awt.Color(102, 0, 0));
        Y.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        PanelTeclas.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 50, 50));

        U.setBackground(new java.awt.Color(102, 0, 0));
        U.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        PanelTeclas.add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, 50));

        I.setBackground(new java.awt.Color(102, 0, 0));
        I.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        PanelTeclas.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 50, 50));

        O.setBackground(new java.awt.Color(102, 0, 0));
        O.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        PanelTeclas.add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 50, 50));

        P.setBackground(new java.awt.Color(102, 0, 0));
        P.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        PanelTeclas.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 50, 50));

        A.setBackground(new java.awt.Color(102, 0, 0));
        A.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        PanelTeclas.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 50));

        S.setBackground(new java.awt.Color(102, 0, 0));
        S.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        PanelTeclas.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 50, 50));

        D.setBackground(new java.awt.Color(102, 0, 0));
        D.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        PanelTeclas.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 50, 50));

        F.setBackground(new java.awt.Color(102, 0, 0));
        F.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        PanelTeclas.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 50, 50));

        G.setBackground(new java.awt.Color(102, 0, 0));
        G.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        PanelTeclas.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 50, 50));

        H.setBackground(new java.awt.Color(102, 0, 0));
        H.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        PanelTeclas.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 50, 50));

        J.setBackground(new java.awt.Color(102, 0, 0));
        J.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        PanelTeclas.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 50, 50));

        K.setBackground(new java.awt.Color(102, 0, 0));
        K.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        PanelTeclas.add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, 50));

        L.setBackground(new java.awt.Color(102, 0, 0));
        L.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        PanelTeclas.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 50, 50));

        Ñ.setBackground(new java.awt.Color(102, 0, 0));
        Ñ.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Ñ.setText("Ñ");
        Ñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÑActionPerformed(evt);
            }
        });
        PanelTeclas.add(Ñ, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 50, 50));

        Z.setBackground(new java.awt.Color(102, 0, 0));
        Z.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        PanelTeclas.add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 50, 50));

        X.setBackground(new java.awt.Color(102, 0, 0));
        X.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        PanelTeclas.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 50, 50));

        C.setBackground(new java.awt.Color(102, 0, 0));
        C.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        PanelTeclas.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 50));

        V.setBackground(new java.awt.Color(102, 0, 0));
        V.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        PanelTeclas.add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 50, 50));

        B.setBackground(new java.awt.Color(102, 0, 0));
        B.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        PanelTeclas.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 50, 50));

        N.setBackground(new java.awt.Color(102, 0, 0));
        N.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        PanelTeclas.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 50, 50));

        M.setBackground(new java.awt.Color(102, 0, 0));
        M.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        PanelTeclas.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 50, 50));

        Zero.setBackground(new java.awt.Color(102, 0, 0));
        Zero.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });
        PanelTeclas.add(Zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 50, 50));

        One.setBackground(new java.awt.Color(102, 0, 0));
        One.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });
        PanelTeclas.add(One, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 50, 50));

        Two.setBackground(new java.awt.Color(102, 0, 0));
        Two.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });
        PanelTeclas.add(Two, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 50, 50));

        Three.setBackground(new java.awt.Color(102, 0, 0));
        Three.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });
        PanelTeclas.add(Three, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 50, 50));

        Four.setBackground(new java.awt.Color(102, 0, 0));
        Four.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });
        PanelTeclas.add(Four, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 50, 50));

        Five.setBackground(new java.awt.Color(102, 0, 0));
        Five.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });
        PanelTeclas.add(Five, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 50, 50));

        Six.setBackground(new java.awt.Color(102, 0, 0));
        Six.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });
        PanelTeclas.add(Six, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 50, 50));

        Seven.setBackground(new java.awt.Color(102, 0, 0));
        Seven.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });
        PanelTeclas.add(Seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 50, 50));

        Eight.setBackground(new java.awt.Color(102, 0, 0));
        Eight.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });
        PanelTeclas.add(Eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 50, 50));

        Nine.setBackground(new java.awt.Color(102, 0, 0));
        Nine.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });
        PanelTeclas.add(Nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 50, 50));

        Intentos.setBackground(new java.awt.Color(255, 255, 255));
        Intentos.setFont(new java.awt.Font("SimSun-ExtB", 3, 18)); // NOI18N
        Intentos.setForeground(new java.awt.Color(0, 0, 0));
        Intentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Intentos.setText("7");
        PanelTeclas.add(Intentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 70, 50, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setLabelFor(Intentos);
        jLabel1.setText("INTENTOS");
        PanelTeclas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("?");
        PanelTeclas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 60, 60, 50));

        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("PISTA");
        PanelTeclas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 50, -1));

        PanelIMG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addComponent(PanelIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        // TODO add your handling code here:
        pega("W");
    }//GEN-LAST:event_WActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        // TODO add your handling code here:
        pega("Q");
        
    }//GEN-LAST:event_QActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        pega("E");
    }//GEN-LAST:event_EActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        // TODO add your handling code here:
        pega("R");
    }//GEN-LAST:event_RActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        // TODO add your handling code here:
        pega("T");
    }//GEN-LAST:event_TActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        // TODO add your handling code here:
        pega("Y");
    }//GEN-LAST:event_YActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
        pega("U");
    }//GEN-LAST:event_UActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
        pega("I");
    }//GEN-LAST:event_IActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        // TODO add your handling code here:
        pega("O");
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
        pega("P");
    }//GEN-LAST:event_PActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        pega("A");
    }//GEN-LAST:event_AActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
        pega("S");
    }//GEN-LAST:event_SActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        pega("D");
    }//GEN-LAST:event_DActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        pega("F");
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        // TODO add your handling code here:
        pega("G");
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
        pega("H");
    }//GEN-LAST:event_HActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        // TODO add your handling code here:
        pega("J");
    }//GEN-LAST:event_JActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
        pega("K");
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
        pega("L");
    }//GEN-LAST:event_LActionPerformed

    private void ÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÑActionPerformed
        // TODO add your handling code here:
        pega("Ñ");
    }//GEN-LAST:event_ÑActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        // TODO add your handling code here:
        pega("Z");
    }//GEN-LAST:event_ZActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        pega("X");
    }//GEN-LAST:event_XActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        pega("C");
    }//GEN-LAST:event_CActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
        pega("V");
    }//GEN-LAST:event_VActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        pega("B");
    }//GEN-LAST:event_BActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
        pega("N");
    }//GEN-LAST:event_NActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
        pega("M");
    }//GEN-LAST:event_MActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        // TODO add your handling code here:
        pega("0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        // TODO add your handling code here:
        pega("1");
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        // TODO add your handling code here:pega("W");
        pega("2");
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        // TODO add your handling code here:
        pega("3");
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        // TODO add your handling code here:
        pega("4");
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        // TODO add your handling code here:
        pega("5");
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        // TODO add your handling code here:
        pega("6");
    }//GEN-LAST:event_SixActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        // TODO add your handling code here:
        pega("7");
    }//GEN-LAST:event_SevenActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
        // TODO add your handling code here:
        pega("8");
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        // TODO add your handling code here:
        pega("9");
       
    }//GEN-LAST:event_NineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton Eight;
    private javax.swing.JButton F;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JTextField Intentos;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton Nine;
    private javax.swing.JButton O;
    private javax.swing.JButton One;
    private javax.swing.JButton P;
    private javax.swing.JPanel PanelIMG;
    private javax.swing.JPanel PanelTeclas;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton T;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton Zero;
    private javax.swing.JTextField cuadro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton Ñ;
    // End of variables declaration//GEN-END:variables

   private void pega(String n){
String cadena=cuadro.getText();
cuadro.setText(cadena+n);

} 
}


